@startuml diagrama

title Trabajo Práctico - Plataforma Alquiler de Vehículos

abstract class Vehiculo{
    # matricula : string
    # estado : Estado 
    # kilometraje: number 
    # tarifaBase : number
    # valorCargoExtra: number
    + calcularExtra(kmTotales: number, diasTotales:number)
    
    + gettersYSetters()
}

class Compacto extends Vehiculo{
    + calcularExtra(kmTotales: number, diasTotales:number)

}

class Sedan extends Vehiculo{
    + calcularExtra(kmTotales: number, diasTotales:number)
}
class Suv extends Vehiculo{
    + calcularExtra(kmTotales: number, diasTotales:number)
}

abstract class Estado{
    + gettersYSetters()
}

class Disponible extends Estado{

}

class Alquilado extends Estado{

}

class Limpieza extends Estado{

}

class Mantenimiento extends Estado{

}

abstract class Persona{
    - nombre : string
    - dni : string 
    - email : string

    +gettersYsetters()
}

class Cliente extends Persona{
    
    '+ solicitarReserva(vehiculo: Vehiculo)
    ' Respecto a este método, queda en pausa. Revisar despues.
    ' solicitud cliente -> evaluacion del admin -> generar reserva 

    + devolverVehiculo(vehiculo: Vehiculo)
    
}

class Reserva{
    
    -cliente : Cliente 
    -vehiculo : Vehiculo
    -kmInicio : number
    -kmFin : number 
    -fechaInicio : date
    -fechaFin : date
    -tieneCargosExtra : boolean

    + gettersYsetters()
    + calcularDiasTotales()
    + calcularKmTotales()


}

class CalculadoraTarifa{
    + calcularTarifa(reserva: Reserva)
}

'Admin -> Permisos, CRUD 
'AdminDriveHub -> Sistema de reservas

class Admin {
    - clientes : Array<Cliente>
    - reservas : Array<Reserva>
    - vehiculo : Array<Vehiculo>

    + chequearDisponibilidad()
    + generarReserva()

    + gettersYsetters()
}

Vehiculo*-l-Estado
Admin*-r-Cliente
Reserva*-r-Admin
Reserva*--Vehiculo
Reserva o-l-CalculadoraTarifa

note left of CalculadoraTarifa
    reserva.vehiculo.getTarifaBase() * 
    reserva.calcularDiasTotales() + 
    reserva.vehiculo.calcularExtra(reserva.calcularDiasTotales(), reserva.calcularDiasTotales());
end note


@enduml